core/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls') ),
    path('', include('users.urls') ),
   # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.

#admin and customer models
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

#Products model
class Product(models.Model):
    title = models.CharField(max_length=255, null=True)
    slug = models.SlugField(unique= True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    stock_quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField(null=True)
    expiry_date =models.DateTimeField(null=True)
    view_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    # def get_absolute_url(self):
       # return reverse("make_order", kwargs={
      #      "slug": self.slug
       # })
        
   # def get_add_to_orders_url(self):
     #   return reverse("add_to_orders", kwargs={
    #        "slug": self.slug
    #    })
    
    
#Orders Model
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(null= True, auto_now_add=True)
    ordered= models.BooleanField(default=False)
    
    def __str__(self):
        return 'cart: ' + str(self.id)
    
   # def get_total(self):
    #    total = 0
     #   for order_item in self.items.all():
      #      total += order_item.get_final_price()
       # return total
    
     
class CartProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True,blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1)
    subtotal = models.PositiveIntegerField(null=True,blank=True)
    ordered =models.BooleanField(default=False)
    
    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)
    
    #calculate total price
   # def get_total_order_price(self):
    #    return self.quantity * self.item.price
    
    # def get_final_price(self):
      #  return self.get_total_order_price()
    
ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, null=True,blank=True)
    ordered_by = models.CharField(max_length=200,null=True,blank=True)
    shipping_address = models.CharField(max_length=200,null=True,blank=True)
    mobile = models.CharField(max_length=10,null=True,blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField(null=True,blank=True)
    total = models.PositiveIntegerField(null=True,blank=True)
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS, null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True,blank=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")

    def __str__(self):
        return "Order: " + str(self.id)

    
    

templates/skeleton/admins.html
{% extends 'body/base.html' %}
{% block title %}Admins{% endblock  %}


{% block content %}

{% include 'body/navbar.html' %}

 <!--Table-->
 <div class="container">
    <div class="row my-4">
        <div class="col-md-4"></div>
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <th scope="row"><a class="btn btn-info btn-sm" href="">View</a></th>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>



<!--End Table-->

{% endblock  %}

templates/skeleton/checkout.html
{% extends "body/base.html" %}
{% block title %}Details{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                   Checkout Panel
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table bg-white table-borderless">
                                <tbody>
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Product</th>
                                            
                                            <th>Quantity</th>
                                            <th>Subtotal</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for cp in cart.cartproduct_set.all %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{cp.product.title}}</td>
                                         
                                            <td>{{cp.quantity}}</td>
                                            <td>{{cp.subtotal}}</td>
                                        </tr>
                                        {% endfor %}
                                        <tr>
                                            <th colspan="4">Total</th>
                                            <th>$ {{cart.total}}</th>
                                        </tr>
                                </tbody>
                            </table>
                            <hr>
                            <div>
                                <form method='POST'>
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button class="btn btn-info">Place order</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!--End Table-->


{% endblock  %}

templates/skeleton/customers.html
{% extends 'body/base.html' %}  
{% block title %}Orders{% endblock  %}


{% block content %}

{% include 'body/navbar.html' %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">Customner Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">No of Orders</th>
                    </tr>
                </thead>
                <tbody>
                   
                </tbody>
            </table>
        </div>
    </div>

</div>
<!--End Table-->


{% endblock  %}

templates/skeleton/delete.html
{% extends 'body/base.html' %}
{% block title %}Delete{% endblock %}


{% block content %}
<div class='container'>
    <div class='row mt-5'>
        <div class='col-md-6 offset-md-3'>
            <div class='border bg-white p-3'>
                <h4>Delete Stock</h4>
                <hr>
                <div class='alert alert-danger'>
                    <h5>Sure to delete?</h5>
                </div>
                <form method='POST'>
                    {% csrf_token %}
                    {{ form }}
                    <a class='btn btn-primary' href="{% url 'products' %}">Cancel</a>
                    <input class='btn btn-danger' type='submit' value='Delete' />
                </form>
            </div>
          
        </div>
    </div>
</div>



{% endblock %}

templates/skeleton/delete_order.html
{% extends 'body/base.html' %}
{% block title %}Delete Order{% endblock %}


{% block content %}
<div class='container'>
    <div class='row mt-5'>
        <div class='col-md-6 offset-md-3'>
            <div class='border bg-white p-3'>
                <h4>Delete Order</h4>
                <hr>
                <div class='alert alert-danger'>
                    <h5>Sure to delete?</h5>
                </div>
                <form method='POST'>
                    {% csrf_token %}
                    {{ form }}
                    <input class='btn btn-danger' type='submit' value='Delete' />
                </form>
            </div>
          
        </div>
    </div>
</div>



{% endblock %}

templates/skeleton/details.html
{% extends "body/base.html" %}
{% block title %}Details{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                   Order Details
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table bg-white table-borderless">
                                <tbody>
                                    
                                    <tr>
                                        <th scope="row">Product</th>
                                        <td>{{ stock_order.product }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Ordered By</th>
                                        <td>{{ stock_order.order_by }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Quantity Ordered</th>
                                        <td>{{ stock_order.order_quantity }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Price</th>
                                        <td>{{ stock_order.price }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Total Amount</th>
                                        <td>{{ stock_order.total_amount }}</td>
                                    </tr>
                                    <!--<tr>
                                        <th scope="row">Ordered Date</th>
                                        <td>{{ stock_order.order_date }}</td>
                                    </tr>-->
                                </tbody>
                            </table>
                            <hr>
                            <form method='POST'>
                                {% csrf_token %}
                                {{ form|crispy }}
                                <input class='btn btn-success' type='submit' value='Approve' />
                                <a class='btn btn-primary' href="{% url 'delete_order' stock_order.id %}">Delete</a>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!--End Table-->


{% endblock  %}

templates/skeleton/index.html
{% extends 'body/base.html' %}  
{% block title %}Home{% endblock  %}



{% block content %}

{% include 'body/navbar.html' %}

{% endblock %}

templates/skeleton/items_list.html
{% extends 'body/base.html' %}  
{% block title %}Make Order{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}

{% include 'body/navbar.html' %}

  <!--Table-->
  <div class="container">
    <div style="padding-top:25px;"></div>
    <a href='{% url 'my_cart' %}' class='btn btn-danger'>View Cart</a>
    <div class="row my-4">
      
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        
                        <th scope="col">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p  in product_list  %}
                    <tr>
                        <td>{{ p.title }}</td>
                        <td>{{ p.category }}</td>
                        <td>{{ p.price }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{% url 'add_to_cart' p.id %} ">Order</a>
                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>



<!--End Table-->

{% endblock %}

templates/skeleton/make_order.html
{% extends "body/base.html" %}
{% block title %}Submit Order{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}


<!--Table-->
<div class="container">
    <div class='col-md-4'></div>
    {% for message in messages  %}
        {% if message %}
        <div class='alert alert-{{ message.tags }}'>
            {{ message }}
        </div>
        {% endif %}
        {% endfor %}
    <div class="row my-4">
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                   Submit Order
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table bg-white table-borderless">
                                <tbody>
                                    
                                    <tr>
                                        <th scope="row">Product</th>
                                        <td>{{ product.title }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Category</th>
                                        <td>{{ product.category }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Price</th>
                                        <td>{{ product.price }}</td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr>
                            <form method='POST'>
                                {% csrf_token %}
                                {{ form|crispy }}
                            </form>
                            <a href='{% url 'add_to_cart' p.id %}' class='btn btn-success'>Submit</a>
                            <hr>
                            <a href='' class='btn btn-danger'>View Summary</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!--End Table-->


{% endblock  %}

templates/skeleton/my_cart.html
{% extends "body/base.html" %}
{% block title %}Submit Order{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}


<!--Table-->
<div class="container">
    <div class='col-md-4'></div>
    <div class="row my-4">
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                   Cart Products
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table bg-white table-borderless">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Product</th>
                                        <th>Category</th>
                                        <th>Quantity</th>
                                        <th>Subtotal</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cp in cart.cartproduct_set.all %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{cp.product.title}}</td>
                                        <td>{{cp.product.category}}</td>
                                        <td>{{cp.quantity}}</td>
                                        <td>{{cp.subtotal}}</td>
                                        <td class='row'>
                                            <a href="{% url 'manage_cart' cp.id %}?action=inc" > + </a>
                                            <a href="{% url 'manage_cart' cp.id %}?action=dcr" > - </a>
                                            <a href="{% url 'manage_cart' cp.id %}?action=rmv" > x </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <th colspan='4'>Total</th>
                                        <th>$ {{ cart.total }}</th>
                                        {% if cart.cartproduct_set.all %}
                                        <th><a class='btn btn-danger' href='{% url 'empty_cart' %}'>Delete</a></th>
                                        {% endif %}
                                    </tr>
                                   
                                </tbody>
                                <hr />
                                {% if cart.cartproduct_set.all %}
                                <tr>
                                    <th><a class='btn btn-warning' href='{% url 'checkout' %}'>Checkout</a></th>
                                </tr>
                                {% endif %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!--End Table-->


{% endblock  %}

templates/skeleton/order_detail.html
{% extends "body/base.html" %}
{% block title %}Details{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                   Order Details
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table bg-white table-borderless">
                                <tbody>
                                    
                                    <tr>
                                        <th scope="row">Order Id</th>
                                        <td>{{ ord_obj.id }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Status</th>
                                        <td>{{ ord_obj.order_status }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Date Ordered</th>
                                        <td>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Customer Name</th>
                                        <td>{{ ord_obj.ordered_by }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Customer Number</th>
                                        <td>{{ ord_obj.mobile }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Status</th>
                                        <td>{{ ord_obj.order_status }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Payment Method</th>
                                        <td>{{ ord_obj.payment_method }}</td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr>
                            <table class="table bg-white table-borderless">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Item</th>
                                
                                        <th>Quantity</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{cp.product.title}}({{cp.product.id}})</td>
                                        <td>{{cp.quantity}}</td>
                                        <td>{{cp.subtotal}}</td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <th colspan="4" class="text-right">Total: </th>
                                        <th>$ {{ord_obj.total}}</th>
                                    </tr>
                                </tbody>
                            </table>
                            <form action="{% url 'change_status' ord_obj.id %}" method='POST'>
                                {% csrf_token %}
                                <select name="status">
                                    {% for i, j in allstatus %}
                                    <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                                    {% endfor %}
                                </select>
                                <button class='btn btn-primary'>Update</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!--End Table-->


{% endblock  %}

templates/skeleton/order_summary.html
{% extends 'body/base.html' %}  
{% block title %}Orders{% endblock  %}


{% block content %}

{% include 'body/navbar.html' %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Category</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Amount</th>
                      
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.category }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>{{ order_item.quantity }}</td>
                        <td>$ {{ order_item.get_total_order_price }}</td>        
                    </tr>
                    {% endfor %}
                </tbody>
                <tr>
                    <td colspan='5'> Total Order Amount</td>
                    <td colspan='5'><b>$ {{ object.get_total }}</b></td>
                </tr>
                <tr>
                    <td colspan='5'></td>
                    <td>
                        <a class='btn btn-danger float-right ml-2' href="#">Checkout</a>
                    </td>
                    
                </tr>
            </table>
        </div>
    </div>

</div>
<!--End Table-->


{% endblock  %}

templates/skeleton/products.html
{% extends 'body/base.html' %}  
{% block title %}Products{% endblock  %}
{% load crispy_forms_tags %}
{% block content %}

{% include 'body/navbar.html' %}

  <!--Table-->
  <div class="container">
    <div class="row my-4">
        <div class="col-md-4">
        
                {% for message in messages  %}
                {% if message %}
                <div class='alert alert-{{ message.tags }}'>
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
           
            <div class="border bg-white p-3">
                <h4>Add Products</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success btn-block" type="submit" value="Add Product">
                </form>
            </div>
        </div>
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Expiry Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stocks  in stocks  %}
                    <tr>
                        <td>{{ stocks.title }}</td>
                        <td>{{ stocks.category }}</td>
                        <td>{{ stocks.stock_quantity }}</td>
                        <td>{{ stocks.price }}</td>
                        <td>{{ stocks.expiry_date }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{% url 'update' stocks.id %}">Edit</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'delete' stocks.id %}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>



<!--End Table-->

{% endblock %}

templates/skeleton/update.html
{% extends 'body/base.html' %}
{% block title %}Update {% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class='container'>
    <div class='row mt-5'>
        <div class='col-md-6 offset-md-3'>
            <div class='border bg-white p-3'>
                <h4>Update Stock</h4>
                <hr>
                <form method='POST'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class='btn btn-success' type='submit' value='Update' />
                    <a class='btn btn-primary' href="{% url 'products' %}">Cancel</a>
                </form>
            </div>
          
        </div>
    </div>
</div>



{% endblock %}